Add typing for storage keys
wxt-dev/wxt pull request #708
Opened 2024-06-08 19:46 UTC by TheOnlyTails

2024-06-09 03:06 UTC, aklinker1 requested changes
Thanks for the PR! Good change.

A couple of changes and I can get this merged!

2024-06-09 03:06 UTC, aklinker1 commented on pnpm-lock.yaml
I don't think any of these changes are relevant, can you revert the changes to this file?

2024-06-09 03:06 UTC, aklinker1 commented on packages/wxt/src/__tests__/storage.test.ts
Could you add another test with a bad key to ensure types are working? Something like this should be good enough, can probably go outside the main describe for each storage area

```ts
it("should not accept keys without a valid storage area prefix", () => {
  // @ts-expect-error: Test passes if there is a type error here
  storage.getItem("test");
});
```

2024-06-09 06:22 UTC, TheOnlyTails commented on packages/wxt/src/__tests__/storage.test.ts
Done!

2024-06-09 06:25 UTC, TheOnlyTails commented on pnpm-lock.yaml
done

2024-06-09 06:29 UTC, TheOnlyTails commented
This is a bit of a nitpick, but do you know why the auto-generated docs show this in the definition of `StorageItemKey`?
![image](https://github.com/wxt-dev/wxt/assets/65342367/a397b20a-1dde-4468-bf3e-7b79d77e99d9)
https://deploy-preview-708--creative-fairy-df92c4.netlify.app/api/reference/wxt/storage/type-aliases/StorageItemKey.html#type-alias-storageitemkey

2024-06-09 12:26 UTC, aklinker1 approved these changes
> This is a bit of a nitpick, but do you know why the auto-generated docs show this in the definition of `StorageItemKey`?
> ![image](https://github.com/wxt-dev/wxt/assets/65342367/a397b20a-1dde-4468-bf3e-7b79d77e99d9)

Haha nope, that's crazy. I probably need to upgrade the tool, but it's touchy and breaks horribly whenever I try.

2024-06-09 14:20 UTC, merged

2024-06-12 05:55 UTC, aklinker1 commented
Released in [`v0.18.5`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.18.5)