feat(auto-icons): initial module
wxt-dev/wxt pull request #851
Opened 2024-07-24 23:04 UTC by Timeraa

Adds a new module to wxt to automatically generate icons for the manifest `icons` field using sharp

Closes #850

2024-07-24 23:05 UTC, Timeraa commented
@aklinker1 I noticed a small issue with the wxt module system, is there a way to get the module options in hooks? Because right now you would need to restart the whole process in order for the options to update.

2024-07-24 23:12 UTC, aklinker1 commented
Are you saying if someone saves the `wxt.config.ts` file with new options, they aren't updated? Hmmm... Yeah I can see why that would be the case. Let me think on the best way to fix that.

2024-07-24 23:12 UTC, Timeraa commented
> Are you saying if someone saves the `wxt.config.ts` file with new options, they aren't updated? Hmmm... Yeah I can see why that would be the case. Let me think on the best way to fix that.

Yep exactly that! It totally makes sense why but probably something to think about!

2024-07-25 13:45 UTC, aklinker1 requested changes
Code looks good, just a couple of small changes.

What are your thoughts on the `module-` prefix for the package names? I wanted it to be consistent, but now I'm regretting it... `@wxt-dev/auto-icons` is good too 😵‍💫

2024-07-25 13:45 UTC, aklinker1 commented on packages/module-auto-icons/package.json
> +      }
v0.19.0 is queued up and about to be released, the breaking change being dropping CJS support. So you can remove the "require". I should remove it from the other modules as well...

```suggestion
      "types": "./dist/index.d.mts",
      "default": "./dist/index.mjs"
```

2024-07-25 13:45 UTC, aklinker1 commented on packages/module-auto-icons/build.config.ts
> +  externals: ['fs-extra'],
Isn't unbuild already marking `fs-extra` as external? It should see it in the `dependencies` and know to not bundle it.

2024-07-25 14:04 UTC, aklinker1 commented on packages/module-auto-icons/build.config.ts
> +  externals: ['fs-extra'],
Yeah, tested and it's the same output without this file, I removed it in my commit.

2024-07-25 14:04 UTC, aklinker1 commented on packages/module-auto-icons/package.json
> +      }
Added in my commit

2024-07-25 15:12 UTC, aklinker1 commented
Looks like the generated icons aren't added to the internal output structure, and are causing some issues: 

<img width="419" alt="Screenshot 2024-07-25 at 10 10 22 AM" src="https://github.com/user-attachments/assets/c1836f6e-3f2e-4a26-84b9-55cee6d515ea">

And the icons don't show up in the build output.

<img width="713" alt="Screenshot 2024-07-25 at 10 11 42 AM" src="https://github.com/user-attachments/assets/2846231b-a907-4a4b-89a7-00238854d6bc">

Might need to add some more hooks to WXT to fix these issues.

2024-07-25 15:22 UTC, aklinker1 commented
For example, a `prepare:publicPaths` hook here to fix the `browser.runtime.getURL` issue: https://github.com/wxt-dev/wxt/blob/ab234c0f458b4fb62de353130d6971701576e946/packages/wxt/src/core/utils/building/generate-wxt-dir.ts#L78-L90

For the build output issue... I think we can just add the icon files to the `output.publicAssets` file in the `build:done` hook.

```
wxt.hooks.hook("build:done", (wxt, output) => {
  output.publicAssets.push({ type: "asset", file: "icons/16.png");
});
```

2024-07-25 18:00 UTC, Timeraa commented
Oh gosh what did I do to the branch

2024-07-25 18:15 UTC, Timeraa commented
Implemented the requested changes @aklinker1, I also updated the background.ts so that the /icons path is correct in the geturl

2024-07-25 19:49 UTC, aklinker1 approved these changes
> Implemented the requested changes @aklinker1, I also updated the background.ts so that the /icons path is correct in the geturl

Perfect, thanks. Everything looks good now.

> I can make it just auto-icons if ya want, just did fit for consistency haha

Hmmmmmmmmmmmmmmmmmm... Yeah, let's rename it to just `@wxt-dev/auto-icon`

2024-07-26 04:41 UTC, merged